### ISSUE TITLE
Add Link To Webpage In Readme

### ISSUE THREAD

**Issue by lucasscharenbroch** [AndrewDTR/uw-cal-generator#3]
Add the url of the site to the README (or in the settings of the repo).

**Comment by AndrewDTR** [comment]
ah, thank you lucas! just added it to the 'about' section

**Comment by lucasscharenbroch** [comment]
Not sure if you know (or if it makes a difference to you), but there's also a dedicated slot for a link, below the description (see [Nico's site](https://github.com/nicosalm/salm.dev), for example).
